// Internal exports for CLI access
export { useDb, checkTableExists } from '../utils/db.ts'
export { createUser, findUserByEmail, updateUserPassword, getCurrentUserFromToken, hasAnyUsers, deleteExpiredPersonalAccessTokens, deleteTokensWithoutExpiration, cleanupPersonalAccessTokens, revokeUserTokens, getLastLoginTime } from '../utils/user.ts'
export { createUsersTable } from '../utils/create-users-table.ts'
export { createPersonalAccessTokensTable } from '../utils/create-personal-access-tokens-table.ts'
export { createPasswordResetTokensTable } from '../utils/create-password-reset-tokens-table.ts'
export { createMigrationsTable } from '../utils/create-migrations-table.ts'
export { runMigrations } from '../utils/migrate.ts'
export { useNuxtUsersDatabase } from '../composables/useNuxtUsersDatabase.ts'
export { useServerAuth } from '../composables/useServerAuth.ts'
